services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app:delegated
      - /app/node_modules
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: 'md5'

    expose:
      - 5432 
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  db-data:
  redis:
    driver: local
